import { sql } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/**
 * Conventions (they make local ⇄ cloud sync possible later without a rewrite):
 * - every id is a UUIDv7 generated by the app (globally unique, time-ordered);
 * - every row carries its branch (or org) so data from many shops can live in one cloud DB;
 * - money is integer minor units; times are timestamptz;
 * - nothing that touches money is deleted — it is voided, and every change is an `events` row.
 */

const ts = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });
const createdAt = () => ts('created_at').notNull().defaultNow();
const updatedAt = () => ts('updated_at').notNull().defaultNow();

export const organizations = pgTable('organizations', {
  id: uuid('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: createdAt(),
});

export const branches = pgTable('branches', {
  id: uuid('id').primaryKey(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  name: text('name').notNull(),
  timezone: text('timezone').notNull(),
  currency: text('currency').notNull(),
  currencyDecimals: integer('currency_decimals').notNull(),
  locale: text('locale').notNull().default('ar'),
  /** BranchSettings (policies) — validated by @lounge/core on every read. */
  settings: jsonb('settings').$type<unknown>().notNull().default({}),
  billSeq: integer('bill_seq').notNull().default(0),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey(),
    orgId: uuid('org_id').notNull().references(() => organizations.id),
    /** null = every branch (owner). */
    branchId: uuid('branch_id').references(() => branches.id),
    name: text('name').notNull(),
    role: text('role').$type<Role>().notNull(),
    pinHash: text('pin_hash').notNull(),
    active: boolean('active').notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('users_org_idx').on(t.orgId)],
);

export type Role = 'owner' | 'manager' | 'cashier' | 'waiter';

export const stations = pgTable(
  'stations',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    name: text('name').notNull(),
    /** ps5 | vr | … (free text so new device kinds need no migration). */
    type: text('type').notNull(),
    /** regular | vip */
    tier: text('tier').notNull(),
    zone: text('zone').notNull().default(''),
    /** Play modes this station offers, e.g. ["single","multi"] or ["standard"]. */
    modes: jsonb('modes').$type<string[]>().notNull(),
    sort: integer('sort').notNull().default(0),
    maintenance: boolean('maintenance').notNull().default(false),
    maintenanceNote: text('maintenance_note'),
    /** Hardware control config (smart plug / TV) — Phase 3. */
    device: jsonb('device').$type<Record<string, unknown> | null>(),
    active: boolean('active').notNull().default(true),
    /** "Deleted" by the owner: gone from every list, kept so past sessions and bills keep its name. */
    archivedAt: ts('archived_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('stations_branch_idx').on(t.branchId)],
);

export const pricingRules = pgTable('pricing_rules', {
  id: uuid('id').primaryKey(),
  branchId: uuid('branch_id').notNull().references(() => branches.id),
  /** manual = edited in Settings → Pricing; quick = the owner's one-tap "discount now". */
  source: text('source').$type<'manual' | 'quick'>().notNull().default('manual'),
  name: text('name').notNull(),
  priority: integer('priority').notNull().default(0),
  active: boolean('active').notNull().default(true),
  match: jsonb('match').$type<Record<string, unknown>>().notNull(),
  effect: jsonb('effect').$type<Record<string, unknown>>().notNull(),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const packages = pgTable('packages', {
  id: uuid('id').primaryKey(),
  branchId: uuid('branch_id').notNull().references(() => branches.id),
  name: text('name').notNull(),
  minutes: integer('minutes').notNull(),
  price: integer('price').notNull(),
  active: boolean('active').notNull().default(true),
  match: jsonb('match').$type<Record<string, unknown>>().notNull(),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey(),
    orgId: uuid('org_id').notNull().references(() => organizations.id),
    name: text('name').notNull(),
    phone: text('phone'),
    walletBalance: integer('wallet_balance').notNull().default(0),
    notes: text('notes'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('customers_phone_idx').on(t.phone), uniqueIndex('customers_org_phone_uq').on(t.orgId, t.phone)],
);

export const walletTransactions = pgTable('wallet_transactions', {
  id: uuid('id').primaryKey(),
  customerId: uuid('customer_id').notNull().references(() => customers.id),
  branchId: uuid('branch_id').notNull().references(() => branches.id),
  amount: integer('amount').notNull(),
  reason: text('reason').notNull(),
  refId: uuid('ref_id'),
  createdBy: uuid('created_by'),
  createdAt: createdAt(),
});

export type SessionStatus = 'running' | 'ended' | 'closed' | 'void';

export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    kind: text('kind').$type<'open' | 'fixed'>().notNull(),
    plannedMinutes: integer('planned_minutes'),
    packageId: uuid('package_id'),
    customerId: uuid('customer_id'),
    label: text('label'),
    status: text('status').$type<SessionStatus>().notNull(),
    /** Station the session is on now (or ended on). */
    stationId: uuid('station_id').notNull(),
    reservationId: uuid('reservation_id'),
    startedAt: ts('started_at').notNull(),
    endedAt: ts('ended_at'),
    closedAt: ts('closed_at'),
    billId: uuid('bill_id'),
    createdBy: uuid('created_by'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index('sessions_branch_status_idx').on(t.branchId, t.status),
    // The database itself guarantees one running session per station, even if two cashiers click at once.
    uniqueIndex('sessions_station_running_uq').on(t.stationId).where(sql`status = 'running'`),
  ],
);

export const segments = pgTable(
  'segments',
  {
    id: uuid('id').primaryKey(),
    sessionId: uuid('session_id').notNull().references(() => sessions.id),
    stationId: uuid('station_id').notNull(),
    mode: text('mode').notNull(),
    paused: boolean('paused').notNull().default(false),
    startedAt: ts('started_at').notNull(),
    endedAt: ts('ended_at'),
  },
  (t) => [index('segments_session_idx').on(t.sessionId)],
);

export const products = pgTable('products', {
  id: uuid('id').primaryKey(),
  branchId: uuid('branch_id').notNull().references(() => branches.id),
  name: text('name').notNull(),
  category: text('category').notNull(),
  price: integer('price').notNull(),
  trackStock: boolean('track_stock').notNull().default(false),
  stockQty: integer('stock_qty').notNull().default(0),
  lowStockAt: integer('low_stock_at').notNull().default(0),
  /** Pieces per carton, remembered from the last delivery so the next one is prefilled. */
  packSize: integer('pack_size'),
  active: boolean('active').notNull().default(true),
  sort: integer('sort').notNull().default(0),
  /** "Deleted" by the owner: gone from every list; sold items keep their own name and price. */
  archivedAt: ts('archived_at'),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export type KitchenStatus = 'new' | 'preparing' | 'ready' | 'served';

export const orders = pgTable(
  'orders',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    /** null = walk-in (counter) order. */
    sessionId: uuid('session_id'),
    billId: uuid('bill_id'),
    status: text('status').$type<'open' | 'billed' | 'void'>().notNull(),
    kitchenStatus: text('kitchen_status').$type<KitchenStatus>().notNull().default('new'),
    label: text('label'),
    note: text('note'),
    createdBy: uuid('created_by'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('orders_branch_status_idx').on(t.branchId, t.status), index('orders_session_idx').on(t.sessionId)],
);

export const orderItems = pgTable(
  'order_items',
  {
    id: uuid('id').primaryKey(),
    orderId: uuid('order_id').notNull().references(() => orders.id),
    productId: uuid('product_id').notNull(),
    name: text('name').notNull(),
    unitPrice: integer('unit_price').notNull(),
    qty: integer('qty').notNull(),
    voided: boolean('voided').notNull().default(false),
    voidReason: text('void_reason'),
    voidedBy: uuid('voided_by'),
    voidedAt: ts('voided_at'),
    createdAt: createdAt(),
  },
  (t) => [index('order_items_order_idx').on(t.orderId)],
);

export const bills = pgTable(
  'bills',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    number: integer('number').notNull(),
    businessDay: text('business_day').notNull(),
    sessionId: uuid('session_id'),
    customerId: uuid('customer_id'),
    shiftId: uuid('shift_id'),
    timeCharge: integer('time_charge').notNull(),
    itemsTotal: integer('items_total').notNull(),
    discountAmount: integer('discount_amount').notNull(),
    discountReason: text('discount_reason'),
    rounding: integer('rounding').notNull(),
    total: integer('total').notNull(),
    paid: integer('paid').notNull(),
    status: text('status').$type<'paid' | 'void'>().notNull(),
    /** Full snapshot: time bill lines, items, checkout totals — the receipt is rebuilt from this. */
    breakdown: jsonb('breakdown').$type<Record<string, unknown>>().notNull(),
    createdBy: uuid('created_by'),
    approvedBy: uuid('approved_by'),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('bills_branch_number_uq').on(t.branchId, t.number),
    index('bills_branch_day_idx').on(t.branchId, t.businessDay),
  ],
);

/**
 * Cash the accountant (or the owner) takes out of the drawer during a shift. It lowers what the drawer
 * should hold, but it is not a sale and not a refund: the day's income does not change and the shift stays open.
 */
export const cashWithdrawals = pgTable(
  'cash_withdrawals',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    shiftId: uuid('shift_id').notNull(),
    businessDay: text('business_day').notNull(),
    /** Positive minor units. */
    amount: integer('amount').notNull(),
    note: text('note'),
    status: text('status').$type<'active' | 'void'>().notNull().default('active'),
    voidReason: text('void_reason'),
    createdBy: uuid('created_by'),
    createdAt: createdAt(),
  },
  (t) => [index('cash_withdrawals_shift_idx').on(t.shiftId), index('cash_withdrawals_branch_day_idx').on(t.branchId, t.businessDay)],
);

export type PaymentMethod = 'cash' | 'card' | 'wallet';
export type PaymentKind = 'payment' | 'prepaid' | 'deposit' | 'refund';

export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    businessDay: text('business_day').notNull(),
    shiftId: uuid('shift_id'),
    billId: uuid('bill_id'),
    sessionId: uuid('session_id'),
    reservationId: uuid('reservation_id'),
    method: text('method').$type<PaymentMethod>().notNull(),
    kind: text('kind').$type<PaymentKind>().notNull(),
    /** Negative for refunds. */
    amount: integer('amount').notNull(),
    note: text('note'),
    createdBy: uuid('created_by'),
    approvedBy: uuid('approved_by'),
    createdAt: createdAt(),
  },
  (t) => [
    index('payments_branch_day_idx').on(t.branchId, t.businessDay),
    index('payments_shift_idx').on(t.shiftId),
    index('payments_session_idx').on(t.sessionId),
  ],
);

export const shifts = pgTable(
  'shifts',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    userId: uuid('user_id').notNull(),
    businessDay: text('business_day').notNull(),
    status: text('status').$type<'open' | 'closed'>().notNull(),
    openedAt: ts('opened_at').notNull(),
    openingFloat: integer('opening_float').notNull(),
    closedAt: ts('closed_at'),
    closedBy: uuid('closed_by'),
    expectedCash: integer('expected_cash'),
    countedCash: integer('counted_cash'),
    variance: integer('variance'),
    note: text('note'),
  },
  (t) => [index('shifts_branch_status_idx').on(t.branchId, t.status)],
);

export type ReservationStatusDb = 'confirmed' | 'checked_in' | 'cancelled' | 'no_show' | 'completed';

export const reservations = pgTable(
  'reservations',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    stationId: uuid('station_id').notNull(),
    customerName: text('customer_name').notNull(),
    customerPhone: text('customer_phone'),
    customerId: uuid('customer_id'),
    startAt: ts('start_at').notNull(),
    minutes: integer('minutes').notNull(),
    mode: text('mode').notNull(),
    deposit: integer('deposit').notNull().default(0),
    status: text('status').$type<ReservationStatusDb>().notNull(),
    sessionId: uuid('session_id'),
    /** Part of the deposit kept by the shop (late cancel / no-show). */
    fee: integer('fee').notNull().default(0),
    /** Part of the deposit already given back. */
    refunded: integer('refunded').notNull().default(0),
    cancelledAt: ts('cancelled_at'),
    note: text('note'),
    /** "Deleted" from the bookings list. Any deposit money stays in the ledger. */
    archivedAt: ts('archived_at'),
    createdBy: uuid('created_by'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('reservations_branch_start_idx').on(t.branchId, t.startAt)],
);

export const stockMovements = pgTable(
  'stock_movements',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    productId: uuid('product_id').notNull(),
    delta: integer('delta').notNull(),
    reason: text('reason').$type<'sale' | 'void' | 'purchase' | 'adjust' | 'count'>().notNull(),
    refId: uuid('ref_id'),
    /** Deliveries: how many cartons of how many pieces, at what price per piece. */
    cartons: integer('cartons'),
    packSize: integer('pack_size'),
    unitPrice: integer('unit_price'),
    note: text('note'),
    businessDay: text('business_day').notNull(),
    createdBy: uuid('created_by'),
    createdAt: createdAt(),
  },
  (t) => [index('stock_movements_branch_day_idx').on(t.branchId, t.businessDay)],
);

/**
 * Numbered game controllers. `stationId` = where it is now (null = spare on the shelf or on the
 * charger). Charging controllers become ready by themselves when `readyAt` passes.
 */
export const controllers = pgTable(
  'controllers',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    number: integer('number').notNull(),
    stationId: uuid('station_id'),
    status: text('status').$type<'ready' | 'charging' | 'broken'>().notNull().default('ready'),
    chargingSince: ts('charging_since'),
    readyAt: ts('ready_at'),
    note: text('note'),
    active: boolean('active').notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('controllers_branch_number_uq').on(t.branchId, t.number)],
);

/**
 * A session still open when a business day closed (e.g. playing 9 pm → 3 am across midnight): what it
 * had earned by the day's end — time played and drinks taken — belongs to that day's income. Its
 * bill, paid on a later day, counts only the rest there. A void writes the negative back.
 */
export const dayCarries = pgTable(
  'day_carries',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    sessionId: uuid('session_id').notNull(),
    /** The business day this part belongs to. */
    businessDay: text('business_day').notNull(),
    time: integer('time').notNull(),
    items: integer('items').notNull(),
    /** Play time in this part (for the stations' minutes). */
    ms: integer('ms').notNull().default(0),
    createdAt: createdAt(),
  },
  (t) => [index('day_carries_branch_day_idx').on(t.branchId, t.businessDay), index('day_carries_session_idx').on(t.sessionId)],
);

/**
 * A free time earned by a long session ("People Rewards"), kept for the customer's phone number until
 * it is used on a later bill. Never deleted: a wrong one is voided with a reason.
 */
export const rewards = pgTable(
  'rewards',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    customerId: uuid('customer_id').notNull().references(() => customers.id),
    /** The session that earned it — one reward per session. */
    earnedSessionId: uuid('earned_session_id').notNull(),
    earnedDay: text('earned_day').notNull(),
    /** The free time (minutes) and how long the session played (for the message). */
    minutes: integer('minutes').notNull(),
    playedMinutes: integer('played_minutes').notNull(),
    status: text('status').$type<'available' | 'used' | 'void'>().notNull().default('available'),
    usedAt: ts('used_at'),
    usedSessionId: uuid('used_session_id'),
    usedBillId: uuid('used_bill_id'),
    /** When the cashier opened WhatsApp with the message (we cannot know it was sent). */
    notifiedAt: ts('notified_at'),
    voidReason: text('void_reason'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('rewards_earned_session_uq').on(t.earnedSessionId),
    index('rewards_branch_status_idx').on(t.branchId, t.status),
    index('rewards_customer_idx').on(t.customerId),
  ],
);

/** One row per business day. Exactly one is open per branch; closing it opens the next. */
export const businessDays = pgTable(
  'business_days',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull().references(() => branches.id),
    day: text('day').notNull(),
    status: text('status').$type<'open' | 'closed'>().notNull(),
    openedAt: ts('opened_at').notNull(),
    closedAt: ts('closed_at'),
    closedBy: uuid('closed_by'),
    auto: boolean('auto').notNull().default(false),
    /** Hidden from the ledger by "start from now" (the rows stay). */
    archived: boolean('archived').notNull().default(false),
    report: jsonb('report').$type<Record<string, unknown> | null>(),
  },
  (t) => [uniqueIndex('business_days_branch_day_uq').on(t.branchId, t.day)],
);

/** Audit log + sync outbox. Append-only. */
export const events = pgTable(
  'events',
  {
    id: uuid('id').primaryKey(),
    branchId: uuid('branch_id').notNull(),
    type: text('type').notNull(),
    entity: text('entity').notNull(),
    entityId: uuid('entity_id'),
    payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}),
    actorId: uuid('actor_id'),
    approvedBy: uuid('approved_by'),
    reason: text('reason'),
    createdAt: createdAt(),
    syncedAt: ts('synced_at'),
  },
  (t) => [index('events_branch_created_idx').on(t.branchId, t.createdAt), index('events_synced_idx').on(t.syncedAt)],
);
